### PR TITLE
Report on shortcodes

### PR DESCRIPTION
**Pull request by kaedroho**

### CODE REVIEW

**Comment by kaedroho** [comment]
@nickmoreton This is ready for review now

**Comment by nickmoreton** [comment]
@kaedroho Thanks this is working OK. I think we may need a chat around using the individual styles though. Do you have in mind a different approach to the one in place just now: `fix_styles` which uses BS4?

**Comment by kaedroho** [comment]
@nickmoreton since each style rule is unrelated (except some exceptions such as `position`/`left`/`right`) I thought it would be more useful for us to report on the individual rules instead of the whole style.

For example, for styles like ``font-weight: bold; color: #FF0000;`` we only care about the ``font-weight: bold;`` part so putting each combination of rules in separate lines in the report makes it harder for us to find how many usages of ``font-weight: bold;`` there are on a site.

What do you think?

#47 Issue added for this.

**Comment by nickmoreton** [comment]
Hi @kaedroho Im struggling to rectify the conflicts here. 

A previous merge has removed the field mapping we were using: https://github.com/torchbox/wagtail-wordpress-import/commit/829058ab17d8b8fe5c45b08d1c56bc2af26da6c9

Are you able to look at it please? Im not sure how command `analyze_html_content` should be implemented.

**Comment by nickmoreton** [comment]
I updated the title as this PR is only to do with shortcodes now.

**Pull request merged**
